# -*- coding: utf-8 -*-
"""start_up.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KjODgW1TULw-OdBMMVEGAbpheMm0oodN
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import os
import sklearn
data = pd.read_csv("50_Startups.csv")
data.head(10)

sns.distplot(data['Profit'],bins=5,kde=True)

sns.pairplot(data)

sns.barplot(x='State',y='Profit',data=data, palette="Blues_d")

sns.heatmap(data.corr(), annot=True)

g=sns.FacetGrid(data, col='State')
g=g.map(sns.kdeplot,'Profit')

from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
data.iloc[:,3]= labelencoder.fit_transform(data.iloc[:,3].values)
print(data['State'].unique())

print(data.head(10))

X = data.iloc[:, :-1].values
Y = data.iloc[:, 4].values

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, Y_train)

print('Coefficients: \n', regressor.coef_) 
regressor.score(X_train, Y_train)

Y_pred = regressor.predict(X_test)
print(regressor)
Y_pred